### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined for Sass for insude Vue

### ISSUE THREAD

**Issue by akoidan** [AleshaOleg/postcss-sass#120]
> Clearly describe the bug

The sass loops inside of **VUE** files cause linter to crash

> Which rule, if any, is the bug related to?

not related to any rule

> What CSS is needed to reproduce the bug?

Any rule that has `@for` loop in sass

```sass
  $class-slug: for !default

  @for $i from 1 through 4
    .#{$class-slug}-#{$i}
      width: 60px + $i
      color: black
```

> What stylelint configuration is needed to reproduce the bug?

Any rule, is not rule specific. Put something to tigger the linter.

```json
{
  "rules": {
    "color-named": "never"
  }
}
```

> Which version of stylelint are you using?

 11.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?
 
  `./node_modules/.bin/stylelint Sass.vue`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

 Yes, it's related to SASS loops

> What did you expect to happen?

 stylelint would work instead of failing with an error 

> What actually happened (e.g. what warnings or errors did you get)?

An error occured

```text
TypeError: Cannot read property 'start' of undefined
    at LocalFixer.node (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:35:27)
    at /home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:41:9
    at /home/andrew/sass-for/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/andrew/sass-for/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/andrew/sass-for/node_modules/postcss/lib/container.js:131:17)
    at LocalFixer.root (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:40:8)
    at LocalFixer.parse (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:69:9)
    at parseStyle (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:88:39)
    at /home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:103:17
    at Array.forEach (<anonymous>)
```

To reproduce the issue:
 - git clone https://github.com/akoidan/style-sass-for-issue
 - cd style-sass-for-issue
 - yarn install
 - yarn run works
 - yarn run fails

Also [here's](https://stylelint.io/demo#N4Igxg9gJgpiBcIAkYA2BDAzpgtJ1ArgObwAEAZhAE6kCEs56BqALgDoB2nAApTUgEsKVCAFtSARlIsAFiOIzSAFk6lSAOgDEwFBmx5CRAL45tgo6rWkA7gKiyyANgAMABwAepANSlBltZCo1GQARhhgANYgADQgmACeHCzo7ghxWJgx4BAc5AJEacCWbCBUzDCYJWRFHFakJegsOGWoMDgcEDgEHBEd1lwI0mUw0f71IGEQke2dMKKuLPFVQwQjYyWB1DM4AhwAbuiodjgyMO7LLMOjtVYbYqIwSdtzC0uDl6vXdSWwaOhUjQEORwk2mHRwUAIriOYEabVcIlcMCoLAEFWWAG0xmoPmsbnUanVviB8h0qDBMdiiXcOJgYGACKi9m1IdCBLCWBUcLZZBCBORyMjHk0DoR0SAqWoALpUiz40hSr63EC-DAA1HA0ERbaYGTUWToDhQHAIiBIlHxHAQZlUKh2cVkXFKtQlShPRiiASoS3g1kwuHtdAPSrvK7rEBupoer0+zqe7C7Ig4IiPZHsnDR704CIweLWahQC5h+Wu7pgDUcHCw1Bgba7UV2IufcPkMsVquHWvg7qYVzoMAwY1m5GNahNvHE1scctAytHDgwf7JgFQNFPcEdWnJI3-Y2r8kznLj53jHPxcgAh4Q+lqwHA8ECeb6w3sUPNksgB6r9AZxcsAjkoGV7dj0fQDI6xbEr6FQDkaiZ4EiYD8uyAiLMe4a+lC-qcjgjQ7E+KLNOUIYQe+UGdH67IBnSrTltQJErBOyrgi8ix4BAAEDuhH4se4lw-nSnqbLS3HkTs+yHMcUAcWEbT4FgMhVvcwoMU64amuabEgb0ED9KJyo0fSLBbK4dIENJVZ6Lg2lgfpLpxDAtHGVQJpmRZjlzMK2zdDpelvkx9mGXRLmLEi3mgbp4GMSeJSYJc8EbjA1jzhS-kxSA3SoeFvlRWpH54S0bSsZaKUgjAfCpWQWLyvZhzWOg8QhieaiEkS9lnAOCyUjV1ITEEkStPo6DkJyLmYEGbQcBNIL9REg1NZKyp5FQcXtBUnKFhKPXSs1yqktQlWkNVbXEsNo1KaIDxJCUi0yj1cp1Iq4YFeUQFtLCdLLCUQTWMiJTpS9rRvQh-ZtGdf2DA0qD1Y1eCJkDKX-c9TSFXgczshAQSVguyW7GDI0Q2QUMwwtH5apZECYPBIQAgOODFTgpUhOVB1fSAC42kjZOzRTVMcEmNOg2tuMLrhBNUGzdUNaTxLk2glPU7Tk1JUzLPkpL0PSzgojMKijN41zss8-LfMC0rIN08zFUayTcP8wjBsxOG5PDhwitCzjpXgxLkMgFLsM66wAj6wuhvKi7SJu-zILm72QvezbWumw7odO9zUzaq77t03Hltq4dxPS2H9mbC5pzuB2n2+z9EPpaXJxnIzjxELIbO6vqxfjJAl1eQzqvW4Mx29f7MtEq1bUlB1MBdYPi32ctq0LnFg43dtCq7fZ+3q7Pa+BYsrTzk03eiIaUAhrdspjE9H7H151gyKhFR9nTuxU7AieNZ3GwEHFYgmoiyI2J9zxmVAeVUqSF0-mnNq49epTxnuA3e4xvZVh-sZUQ-9hwWk7hPCMAgVpNCXhtVeJ116LRKFvQ6Q9SENHFhdK6r4N57VpPaO2RAU5tC1CQk6d02oPSsNfYkqp-h3krCEQ0SZc741GmzDmtdwzCPVLOEEEiLacPzh-Ue9lFGiJmhnNGQlMb3hViAhOvsR7a11sHRG0DlQ6PbOTQSGMsZqLFjI8xmtYbJzaDY9K9jlGOPRsJVxVtWa+zkT7PxN4REOJ5t4kObQT4V38TkBiEgol-CUZqHm-EvTwSccJTRX8VTRKyZWYJntTHi00ZYoOCTikpPKUYysUi3GE2QZ43A8TfEKNKbo4JrTQnbyJuzGAnNbHaL6e2YBoshlUIgX7TpODSCwOJPA18iDSG1ToY05Zk58GL3WivLapDBEnQoUQMk8ykG0POrfa6EzzkkhYbANhHC9GRG4W1XhRJ+E7RbG2ZRx8fyVNFmYkZFjA56x6R+Kch4mmXQEs-aR7TIFdPhj4x26U4XtmBSEjR4SxnyNhYC4EST6bzDYilBizhsWkuxtND6BcQA10iQC6c7Y+zkiSKcOk1kTGi1fvaGpULrFYvZfCk0-xhS8q5K0oV79CU2jeZi1OdKOXKPvo-Vp4KOkk2KbsWASRRHLAAEzpVaPzXkAAvZEnQQKoTsuMclMyHSSHSl+AQP5BSNAAu9ZprjdVouKZ671f4-VKRcYMglIyIkhsHF638vrAJTSvEytmrL43fiTf+QCXKZUVDlci8Sb9mVxseSUUNOaI0An5m0LBo4xrFqDYs-VFbPwJrDcmtotaUxWnNI2-FYC9VF3bVWgAjqsKgJUBCrTxaClFPsIWdNqdC8VH4J1TpnXO+4SL47VI8bbbp67iSbuRNuo+u6h1hNjUStlPFZiY25A-TkUinUlHBPGU29MjRWnIOxTiysRaHTylBAgohmYuVaOgVc0dbUiCKe2jg4HIPbFyfOJM8HKbvpABpQBlp03V10sS4kqNXWgJvUdBZkKrH1MeS1chIB1ndS2eMBehCjmbVukwi5VyWNbNuciehwovlEh+XUP5ZCPxBWcrhFg8UQiMk4bTHMLAunFoVWWu9xSZNbEaAppT-aRyyZ1Qe294z0q6Zcvpu0imcINpM8WuZsjtPtqsxdEIuxB2mfccuttlmPLBQ815xzQtnOHtHQFpyWxYCYFglAF8wWpqyY3MCN9aVwzuaODuxFwsvZmZHVAqLRktjZcvbl6Nw6P2ueK0Fl1lKZ1L2WLSzLgXZOmRgOZTofx9CEZGZmtzbWTJuW61ZKV3LZCFvU0LTTLmLOteiy5DrXX6atAYZXZlA3avtZG6tzyTwKkQGSBWNm0kCCyR00NkK8Qwp9fGFt8MmUj5YE28R+9xJRSrH1jlk+eWqm+cK7gUVdH0qfcxT9vddMW0WOPWq8MYPvvld+5Vyj1X5sfgR2V7WKQKWvASTSywcojAgCMEAA) the demo

**Comment by AleshaOleg** [comment]
@akoidan sorry, `@for` is not supported yet 🤷‍♂️
https://github.com/AleshaOleg/postcss-sass/issues/53

**Comment by akoidan** [comment]
Any ETA?

**Comment by AleshaOleg** [comment]
Released in `0.4.2`

**Comment by AleshaOleg** [comment]
https://github.com/stylelint/stylelint/pull/4408

**Comment by akoidan** [comment]
@AleshaOleg still doesn't work. The example above provides this error. Please mind the extension is 'vue' not 'sass'
```text
: npm ls |grep postcss-sass
│ ├─┬ postcss-sass@0.4.2
```

```text
✖ ｢wdm｣: TypeError: Cannot read property 'syntax' of undefined
    at /home/andrew/WebstormProjects/vue-webpack-typescript/src/assets/sass/mixins.sass:27:5
    at Declaration.toString (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/patch-postcss.js:38:67)
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/stylelint/lib/rules/color-hex-case/index.js:27:50
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:190:18
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:131:17)
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:148:24
    at Rule.each (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:131:17)
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-sass/node_modules/postcss/lib/container.js:148:24
```
```text
: cat ./node_modules/postcss-sass/package.json  |grep version
  "version": "0.4.2",
```

**Comment by AleshaOleg** [comment]
Probably an extension might be an issue, unfortunately.
Error on this line - https://github.com/gucong3000/postcss-syntax/blob/master/patch-postcss.js#L38.

Hello, @gucong3000. Can you please help us to figure out, what's wrong here? And how we can skip unsupported rules? Thanks!

**Comment by AleshaOleg** [comment]
@alpaca-tc did you already try new version somewhere? Is it working for you?

**Comment by akoidan** [comment]
@AleshaOleg seems like `@for` works now with freshly-released `stylelint:12.0.0`. Needs more testing though...

**Comment by akoidan** [comment]
Nah, wrong still crases in [some cases](https://github.com/akoidan/vue-webpack-typescript/blob/dbe6f4295a65d6f4ff14722f6458c3c864325418/src/components/pages/FilteredUsersPage.vue#L47) mind the branch `crash`

**Comment by soryngitlan** [comment]
```
<style lang="scss" scoped>
  .ip-ranges {
    grid-template: 'ipInput addButton' / 1fr auto;
    display: grid;
    grid-gap: 10px;
    align-items: center;

    $areas: ipInput addButton;

    @each $area in $areas {
      .#{$area} { grid-area: $area; }
    }

    .ipInput { margin-bottom: 0; }
  }
</style>
```

|Packge|Version|
|---------|:-------:|
| stylelint | ^13.7.0 |
| stylelint-config-recess-order | ^2.1.0 |
| stylelint-config-standard | ^20.0.0 |
| stylelint-scss | ^3.18.0 |
| stylelint-webpack-plugin | ^2.1.0 |

Having the same issue: `Stylelint: Unknown word (CssSyntaxError)`.  When trying to use **@each** it shows me the error and doesn't lint anymore.

**Comment by mbinet** [comment]
Hi guys, 

this issue makes stylelint unusable with SASS.

Have you had the chance to make some progress fixing it?
Even only skipping the error would be great, because for now the only workaround is to disable stylelint entirely... 😞

I'm happy to help, write a PR or anything but I have to idea how to fix this!

**Comment by valentinoli** [comment]
I'm getting the same error when applying a media query in Vuetify with map-get like this

```sass
<style lang="sass">
  @import '~vuetify/src/styles/styles.sass'

  @media #{map-get($display-breakpoints, 'md-and-down')}
    .custom-class
      display: none
</style>
```

I don't know what's happening but I suspect that internally `@each` is called to resolve the media query

**Comment by Fischer-L** [comment]
There is a similar issue with a simple `@media` rule, like below
```sass
<style lang="sass">
.page
  &-box
     width: 456px
  @media screen and (max-width: 123px)
    &-box
      width: 123px
<style>
```

**Comment by mktcode** [comment]
I just ran into the same problem now and then realized that I already used a workaround months ago:

```sass
=fix-postcss-bug
  @media screen and (max-width: 1000px)
    .about
      border: solid 100px red
+fix-postcss-bug
```
